### PR TITLE
Order on payroll

### PR DESCRIPTION
**Pull request by abubakar105**
Sir order on the payroll is applied please review the code .

### CODE REVIEW

**Review by AbubakarZorrain — CHANGES_REQUESTED** [review]
Where is the model for Payroll?

**Comment by abubakar105** [comment]
> Where is the model for Payroll?

Sir the Updated code according to your instruction is in the payroll pagination and i have generated a Review request for that. Which i have just updated and raised a review request.

**Comment by AbubakarZorrain** [comment]
> > Where is the model for Payroll?
> 
> Sir the Updated code according to your instruction is in the payroll pagination and i have generated a Review request for that. Which i have just updated and raised a review request.

Before that, it cannot be merged.

**Review by AbubakarZorrain — COMMENTED** [review]
Approved...

**Pull request merged**
